import { InMemoryDbService } from 'angular-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    let employees = [
      {id: 1, first_name: 'Fusce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 2, first_name: 'Augue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 3, first_name: 'Lorem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 4, first_name: 'Amet', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 5, first_name: 'Integer', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 6, first_name: 'Libero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 7, first_name: 'Dapibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 8, first_name: 'Nulla', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 9, first_name: 'Nibh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 10, first_name: 'Saguittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 11, first_name: 'Fusuce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 12, first_name: 'Auguue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 13, first_name: 'Loruem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 14, first_name: 'Loruem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 15, first_name: 'Ameut', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 16, first_name: 'Intueger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 17, first_name: 'Libuero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 18, first_name: 'Dapuibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 19, first_name: 'Nulula', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 20, first_name: 'Nibuh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 30, first_name: 'Saguittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 31, first_name: 'Fusuce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 32, first_name: 'Auguue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 33, first_name: 'Loruem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 34, first_name: 'Ameut', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 35, first_name: 'Intueger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 36, first_name: 'Libuero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 37, first_name: 'Dapibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 38, first_name: 'Nuplla', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 39, first_name: 'Nipbh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 40, first_name: 'Nipbh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 41, first_name: 'Fupsce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 42, first_name: 'Aupgue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 43, first_name: 'Loprem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 44, first_name: 'Ampet', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 45, first_name: 'Inpteger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 46, first_name: 'Lipbero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 47, first_name: 'Dappibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 48, first_name: 'Nuplla', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 49, first_name: 'Nipbh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 50, first_name: 'Sapgittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 51, first_name: 'Fupsce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 52, first_name: 'Aupgue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 53, first_name: 'Loprem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 54, first_name: 'Amuet', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 55, first_name: 'Inuteger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 56, first_name: 'Liubero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 57, first_name: 'Daupibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 58, first_name: 'Nuulla', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 59, first_name: 'Niubh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 60, first_name: 'Saugittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 61, first_name: 'Fuusce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 62, first_name: 'Auugue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 63, first_name: 'Lourem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 64, first_name: 'Amuet', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 65, first_name: 'Inuteger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 66, first_name: 'Liubero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 67, first_name: 'Daupibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 68, first_name: 'Nuulla', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 69, first_name: 'Niubh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 70, first_name: 'Saugittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 214, first_name: 'Amet', middle_name: 'Sociuosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 215, first_name: 'Integer', middle_name: 'Sued', last_name: 'Magneta', role: 'Developer'},
      {id: 216, first_name: 'Libero', middle_name: 'Quuis', last_name: 'RubberMan', role: 'PM'},
      {id: 217, first_name: 'Dapibus', middle_name: 'Eulementum', last_name: 'Dynama', role: 'Developer'},
      {id: 218, first_name: 'Nulla', middle_name: 'Nulula', last_name: 'Dr IQ', role: 'Developer'},
      {id: 218, first_name: 'Nulla', middle_name: 'Nulula', last_name: 'Dr IQ', role: 'Developer'},
      {id: 219, first_name: 'Nibh', middle_name: 'Liguula', last_name: 'Magma', role: 'PM'},
      {id: 220, first_name: 'Sagittis', middle_name: 'uInceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 211, first_name: 'Fusce', middle_name: 'Necu', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 212, first_name: 'Augue', middle_name: 'Semuper', last_name: 'Narco', role: 'PM'},
      {id: 213, first_name: 'Lorem', middle_name: 'Ipsuum', last_name: 'Bombasto', role: 'Developer'},
      {id: 313, first_name: 'Lorem', middle_name: 'Ipstum', last_name: 'Bombasto', role: 'Developer'},
      {id: 314, first_name: 'Amet', middle_name: 'Socitosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 315, first_name: 'Integer', middle_name: 'Sted', last_name: 'Magneta', role: 'Developer'},
      {id: 316, first_name: 'Libero', middle_name: 'Qutis', last_name: 'RubberMan', role: 'PM'},
      {id: 317, first_name: 'Dapibus', middle_name: 'Etlementum', last_name: 'Dynama', role: 'Developer'},
      {id: 318, first_name: 'Nulla', middle_name: 'Nultla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 319, first_name: 'Nibh', middle_name: 'Ligutla', last_name: 'Magma', role: 'PM'},
      {id: 320, first_name: 'Sagittis', middle_name: 'tInceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 311, first_name: 'Fusce', middle_name: 'Nect', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 312, first_name: 'Augue', middle_name: 'Semtper', last_name: 'Narco', role: 'PM'},
      {id: 383, first_name: 'Lorem', middle_name: 'Ipstum', last_name: 'Bombasto', role: 'Developer'},
      {id: 384, first_name: 'Amet', middle_name: 'Socitosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 385, first_name: 'Integer', middle_name: 'Sted', last_name: 'Magneta', role: 'Developer'},
      {id: 385, first_name: 'Inmteger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 386, first_name: 'Limbero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 387, first_name: 'Dampibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 388, first_name: 'Numlla', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 389, first_name: 'Nimbh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 380, first_name: 'Samgittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 381, first_name: 'Fumsce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 382, first_name: 'Aumgue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 413, first_name: 'Lomrem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 414, first_name: 'Ammet', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 415, first_name: 'Inmteger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 416, first_name: 'Limbero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 417, first_name: 'Dampibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 418, first_name: 'Numlla', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 419, first_name: 'Nimbh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 420, first_name: 'Samgittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 411, first_name: 'Fumsce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 411, first_name: 'Fumsce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 412, first_name: 'Aumgue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 453, first_name: 'Lorem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 454, first_name: 'Amet', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 455, first_name: 'Integer', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 456, first_name: 'Libero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 457, first_name: 'Dapibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 458, first_name: 'Nulla', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 459, first_name: 'Nibh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 450, first_name: 'Sagittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 511, first_name: 'Fusce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 512, first_name: 'Augue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 512, first_name: 'Augue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 513, first_name: 'Lorem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 514, first_name: 'Amet', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 515, first_name: 'Integer', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 516, first_name: 'Libero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 516, first_name: 'Libero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 517, first_name: 'Dapibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 518, first_name: 'Nulla', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 519, first_name: 'Nibh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 520, first_name: 'Saguittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 551, first_name: 'Fusuce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 552, first_name: 'Auguue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 553, first_name: 'Loruem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 554, first_name: 'Ameut', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 555, first_name: 'Intueger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 556, first_name: 'Libuero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 620, first_name: 'Saguittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 611, first_name: 'Fusuce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 612, first_name: 'Auguue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 613, first_name: 'Loruem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 614, first_name: 'Ameut', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 615, first_name: 'Intueger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 616, first_name: 'Libuero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 617, first_name: 'Dapuibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 618, first_name: 'Nulula', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 619, first_name: 'Nibh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 720, first_name: 'Sagittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 711, first_name: 'Fusce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 712, first_name: 'Augue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 713, first_name: 'Lorem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 714, first_name: 'Amet', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 715, first_name: 'Integer', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 716, first_name: 'Libuero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 717, first_name: 'Dapuibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 718, first_name: 'Nulula', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 815, first_name: 'Intueger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 816, first_name: 'Libuero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 817, first_name: 'Dapuibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 818, first_name: 'Nulula', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 819, first_name: 'Nibuh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 820, first_name: 'Saguittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 811, first_name: 'Fusuce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 812, first_name: 'Auguue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 813, first_name: 'Loruem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 814, first_name: 'Ameut', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 916, first_name: 'Libuero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 917, first_name: 'Dapuibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 918, first_name: 'Nulula', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
      {id: 919, first_name: 'Nibuh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 920, first_name: 'Saguittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 911, first_name: 'Fusuce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 912, first_name: 'Auguue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 913, first_name: 'Loruem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 914, first_name: 'Ameut', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 915, first_name: 'Intueger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 1019, first_name: 'Niubh', middle_name: 'Ligula', last_name: 'Magma', role: 'PM'},
      {id: 1020, first_name: 'Saugittis', middle_name: 'Inceptos', last_name: 'Tornado', role: 'Developer'},
      {id: 1011, first_name: 'Fuusce', middle_name: 'Nec', last_name: 'Mr. Nice', role: 'Developer'},
      {id: 1012, first_name: 'Auugue', middle_name: 'Semper', last_name: 'Narco', role: 'PM'},
      {id: 1013, first_name: 'Lourem', middle_name: 'Ipsum', last_name: 'Bombasto', role: 'Developer'},
      {id: 1014, first_name: 'Amuet', middle_name: 'Sociosqu', last_name: 'Celeritas', role: 'Developer'},
      {id: 1015, first_name: 'Inuteger', middle_name: 'Sed', last_name: 'Magneta', role: 'Developer'},
      {id: 1016, first_name: 'Liubero', middle_name: 'Quis', last_name: 'RubberMan', role: 'PM'},
      {id: 1017, first_name: 'Daupibus', middle_name: 'Elementum', last_name: 'Dynama', role: 'Developer'},
      {id: 1018, first_name: 'Nuulla', middle_name: 'Nulla', last_name: 'Dr IQ', role: 'Developer'},
    ];
    return {employees};
  }
}
